image: php:7.4

test:
  stage: test
  script:
    - apt-get update && apt-get -y install wget git zip build-essential libzip-dev 
    - wget https://getcomposer.org/download/latest-stable/composer.phar && chmod +x composer.phar
    - mv composer.phar /usr/local/bin/composer
    - composer install
    - vendor/bin/phpunit tests --coverage-clover=coverage.xml
  artifacts:
    paths:
      - coverage.xml
    when: always
    expire_in: 1 day