image: php:7.1

test:
  stage: test
  script:
    - composer install
    - vendor/bin/phpunit tests --coverage-clover=coverage.xml
  artifacts:
    paths:
      - coverage.xml
    when: always
    expire_in: 1 day